#!sh

pidof tini >/dev/null 2>&1 && [[ -f /.env ]] && source /.env && rm /.env || printenv | sed -e 's/^/export /' -e 's/=/="/' -e 's/$/"/' > /.env
pidof tini >/dev/null 2>&1 || exec env - ${TINI_SUBREAPER:+TINI_SUBREAPER=$TINI_SUBREAPER} "$(command -v tini)" -- "$0" "$@"